#include "board_lcd.h"

extern I2C_HandleTypeDef hi2c1;

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_I2C1_Init();     // auto-generated by CubeMX
    lcd_init();

    lcd_goto(0, 0);
    lcd_send_string("Hello Boss!");

    lcd_goto(1, 0);
    lcd_send_string("STM32 + LCD I2C");

    while (1)
    {
        // Optional: refresh or scroll
    }
}
