#include "main.h"
#include "gpio_driver.h"

#define LED_PORT GPIOC
#define LED_PIN  GPIO_PIN_13

int main(void)
{
    HAL_Init();
    SystemClock_Config(); // autogenerated by CubeMX

    // Initialize LED pin
    GPIO_InitPin(LED_PORT, LED_PIN, GPIO_MODE_OUTPUT);

    while (1)
    {
        GPIO_TogglePin(LED_PORT, LED_PIN); // Toggle PC13
        HAL_Delay(500); // Delay 500 ms
    }
}
